services :
  my-app :
    image: riyavyas7/docker-compose-demo:1
    ports :
      - 3000:3000
    environment :
      MONGO_DB_USERNAME: ${MONGO_DB_USER}
      MONGO_DB_PWD: ${MONGO_DB_PASS}
  mongo-db :
    image : mongo
    ports :
      - 27017:27017
    environment :
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
  mongo-express :
    image : mongo-express
    ports :
      - 8081:8081
    environment :
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASS}
    depends_on :
      - mongo-db
