services :
  my-app :
    build: .
    ports :
      - 3000:3000
    environment :
      MONGO_DB_USERNAME: admin
      MONGO_DB_PWD: admin
  mongo-db :
    image : mongo
    ports :
      - 27017:27017
    environment :
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-express :
    image : mongo-express
    ports :
      - 8081:8081
    environment :
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on :
      - mongo-db
